// <auto-generated />
using System;
using BE_HQTCSDL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BE_HQTCSDL.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260812125752_ResyncAllIdentityColumns")]
    partial class ResyncAllIdentityColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE_HQTCSDL.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("THUMBNAIL");

                    b.HasKey("Id");

                    b.ToTable("CATEGORIES");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CONTENT");

                    b.Property<long>("ConversationId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CONVERSATION_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IS_READ");

                    b.Property<long?>("SenderId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SENDER_ID");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("SENDER_TYPE");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("CHAT_MESSAGES", null, t =>
                        {
                            t.HasCheckConstraint("CK_CHAT_MESSAGES_SENDER_ID", "((\"SENDER_TYPE\" IN ('CUSTOMER', 'STAFF') AND \"SENDER_ID\" IS NOT NULL) OR (\"SENDER_TYPE\" IN ('AI', 'SYSTEM') AND \"SENDER_ID\" IS NULL))");

                            t.HasCheckConstraint("CK_CHAT_MESSAGES_SENDER_TYPE", "\"SENDER_TYPE\" IN ('CUSTOMER', 'STAFF', 'AI', 'SYSTEM')");
                        });
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Conversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignedStaffId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ASSIGNED_STAFF_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<long>("CustomerId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<long?>("OrderId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ORDER_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TYPE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("CONVERSATIONS", null, t =>
                        {
                            t.HasCheckConstraint("CK_CONVERSATIONS_STATUS", "\"STATUS\" IN ('AI_ACTIVE', 'WAITING_STAFF', 'STAFF_ACTIVE', 'CLOSED')");

                            t.HasCheckConstraint("CK_CONVERSATIONS_TYPE", "\"TYPE\" IN ('GENERAL_SUPPORT', 'ORDER_SUPPORT')");
                        });
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Inventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<long>("ProductId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITY");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RESERVED_QUANTITY");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("INVENTORY");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("AMOUNT");

                    b.Property<long>("CustomerId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<long>("DiscountAmount")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DISCOUNT_AMOUNT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("NOTE");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ORDER_DATE");

                    b.Property<string>("OrderEmail")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ORDER_EMAIL");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ORDER_STATUS");

                    b.Property<long?>("PaymentMethodId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PAYMENT_METHOD_ID");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("SHIPPING_ADDRESS");

                    b.Property<long?>("VoucherId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("VOUCHER_ID");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("VoucherId");

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ORDER_ID");

                    b.Property<long>("Price")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PRICE");

                    b.Property<long>("ProductId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITY");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SKU");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ORDER_DETAILS");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("AMOUNT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<long>("OrderId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ORDER_ID");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PAID_AT");

                    b.Property<long>("PaymentMethodId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PAYMENT_METHOD_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TRANSACTION_ID");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("PAYMENTS");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.PaymentMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("METHOD_NAME");

                    b.HasKey("Id");

                    b.ToTable("PAYMENT_METHODS");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CardId")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("CARD_ID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("Descriptions")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRIPTIONS");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("IMAGE");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NAME");

                    b.Property<long?>("OriginalPrice")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ORIGINAL_PRICE");

                    b.Property<long?>("Price")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PRICE");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PRODUCT_TYPE");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SKU");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("THUMBNAIL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("WEIGHT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("PRODUCTS");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.ProductCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<long>("ProductId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PRODUCT_ID");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId", "CategoryId")
                        .IsUnique();

                    b.ToTable("PRODUCT_CATEGORIES");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXPIRES_AT");

                    b.Property<int>("IsRevoked")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IS_REVOKED");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("TOKEN");

                    b.Property<long>("UserId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("REFRESH_TOKENS");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REVIEW_COMMENT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<long>("OrderId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ORDER_ID");

                    b.Property<long>("ProductId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Rating")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RATING");

                    b.Property<long>("UserId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId", "OrderId")
                        .IsUnique();

                    b.ToTable("REVIEWS");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.TcgCard", b =>
                {
                    b.Property<string>("CardId")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("CARD_ID");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("CARD_NUMBER");

                    b.Property<string>("ImageLarge")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("IMAGE_LARGE");

                    b.Property<string>("ImageSmall")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("IMAGE_SMALL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Rarity")
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("RARITY");

                    b.Property<string>("SetId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("SET_ID");

                    b.HasKey("CardId");

                    b.HasIndex("SetId");

                    b.ToTable("TCG_CARD");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.TcgSet", b =>
                {
                    b.Property<string>("SetId")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("SET_ID");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("LOGO_URL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("RELEASE_DATE");

                    b.Property<string>("Series")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SERIES");

                    b.Property<int?>("TotalCards")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TOTAL_CARDS");

                    b.HasKey("SetId");

                    b.ToTable("TCG_SET");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("COUNTRY");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("FULL_NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("ROLE");

                    b.HasKey("Id");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.UserAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ADDRESS_NAME");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CITY");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("COUNTRY");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DISTRICT");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("FULL_ADDRESS");

                    b.Property<int>("IsDefault")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IS_DEFAULT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PHONE");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("POSTAL_CODE");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("RECIPIENT_NAME");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<long>("UserId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("WARD");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("USER_ADDRESSES");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Voucher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("DISCOUNT_TYPE");

                    b.Property<long>("DiscountValue")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DISCOUNT_VALUE");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("END_DATE");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("MaxDiscount")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("MAX_DISCOUNT");

                    b.Property<long>("MinOrderValue")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("MIN_ORDER_VALUE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NAME");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("START_DATE");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USAGE_LIMIT");

                    b.HasKey("Id");

                    b.ToTable("VOUCHERS");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Wishlist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ADDED_AT");

                    b.Property<long>("ProductId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<long>("UserId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("WISHLISTS");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.ChatMessage", b =>
                {
                    b.HasOne("BE_HQTCSDL.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_HQTCSDL.Models.User", "Sender")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Conversation", b =>
                {
                    b.HasOne("BE_HQTCSDL.Models.User", "AssignedStaff")
                        .WithMany("AssignedConversations")
                        .HasForeignKey("AssignedStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BE_HQTCSDL.Models.User", "Customer")
                        .WithMany("CustomerConversations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BE_HQTCSDL.Models.Order", "Order")
                        .WithMany("SupportConversations")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedStaff");

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Inventory", b =>
                {
                    b.HasOne("BE_HQTCSDL.Models.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("BE_HQTCSDL.Models.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Order", b =>
                {
                    b.HasOne("BE_HQTCSDL.Models.User", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_HQTCSDL.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");

                    b.HasOne("BE_HQTCSDL.Models.Voucher", "Voucher")
                        .WithMany("Orders")
                        .HasForeignKey("VoucherId");

                    b.Navigation("Customer");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.OrderDetail", b =>
                {
                    b.HasOne("BE_HQTCSDL.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_HQTCSDL.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Payment", b =>
                {
                    b.HasOne("BE_HQTCSDL.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_HQTCSDL.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Product", b =>
                {
                    b.HasOne("BE_HQTCSDL.Models.TcgCard", "Card")
                        .WithMany("Products")
                        .HasForeignKey("CardId");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.ProductCategory", b =>
                {
                    b.HasOne("BE_HQTCSDL.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_HQTCSDL.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.RefreshToken", b =>
                {
                    b.HasOne("BE_HQTCSDL.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Review", b =>
                {
                    b.HasOne("BE_HQTCSDL.Models.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_HQTCSDL.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_HQTCSDL.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.TcgCard", b =>
                {
                    b.HasOne("BE_HQTCSDL.Models.TcgSet", "Set")
                        .WithMany("Cards")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.UserAddress", b =>
                {
                    b.HasOne("BE_HQTCSDL.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Wishlist", b =>
                {
                    b.HasOne("BE_HQTCSDL.Models.Product", "Product")
                        .WithMany("Wishlists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_HQTCSDL.Models.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");

                    b.Navigation("SupportConversations");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Product", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductCategories");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.TcgCard", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.TcgSet", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("AssignedConversations");

                    b.Navigation("ChatMessages");

                    b.Navigation("CustomerConversations");

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("BE_HQTCSDL.Models.Voucher", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
