using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BE_HQTCSDL.Database.Migrations
{
    /// <inheritdoc />
    public partial class ResyncAllIdentityColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var identityTables = new[]
            {
                "CATEGORIES",
                "CHAT_MESSAGES",
                "CONVERSATIONS",
                "INVENTORY",
                "ORDERS",
                "ORDER_DETAILS",
                "PAYMENTS",
                "PAYMENT_METHODS",
                "PRODUCTS",
                "PRODUCT_CATEGORIES",
                "REFRESH_TOKENS",
                "REVIEWS",
                "USERS",
                "USER_ADDRESSES",
                "VOUCHERS",
                "WISHLISTS"
            };

            foreach (var table in identityTables)
            {
                migrationBuilder.Sql(
                    $"ALTER TABLE \"{table}\" MODIFY \"ID\" GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)");
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Advancing identity sequences is intentionally not reversible.
        }
    }
}
