--------------------------------------------------------
--  File: 2026-04-06-native-audit-rbac-run.sql
--  Purpose: Setup DB roles + grants + Oracle Native Unified Audit
--  Schema: CARDGAME
--  Note:
--    1) Run role/grant section as schema owner or privileged account.
--    2) Run audit section as DBA (or account with audit admin privilege).
--------------------------------------------------------

--------------------------------------------------------
-- 0) Safe helper for GRANT statements
--------------------------------------------------------
CREATE OR REPLACE PROCEDURE "CARDGAME"."SP_SAFE_GRANT"
(
    p_sql IN VARCHAR2
)
IS
BEGIN
    EXECUTE IMMEDIATE p_sql;
EXCEPTION
    WHEN OTHERS THEN
        -- Ignore: user/role does not exist, insufficient privilege, duplicate grant
        IF SQLCODE NOT IN (-1917, -1919, -1921, -1031) THEN
            RAISE;
        END IF;
END;
/

--------------------------------------------------------
-- 1) Create DB roles (ignore if already exists)
--------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE CG_APP_USER';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1921 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE CG_ORDER_MANAGER';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1921 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE CG_INVENTORY_MANAGER';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1921 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE CG_ADMIN';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1921 THEN
            RAISE;
        END IF;
END;
/

--------------------------------------------------------
-- 2) Grants for CG_APP_USER
--------------------------------------------------------
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."PRODUCTS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."CATEGORIES" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."PRODUCT_CATEGORIES" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."INVENTORY" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."VOUCHERS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."PAYMENT_METHODS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."TCG_SET" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."TCG_CARD" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."VW_USERS_PUBLIC" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."USER_ADDRESSES" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."WISHLISTS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE ON "CARDGAME"."ORDERS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE ON "CARDGAME"."ORDER_DETAILS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE ON "CARDGAME"."PAYMENTS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."REFRESH_TOKENS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."REVIEWS" TO CG_APP_USER'); END;
/

--------------------------------------------------------
-- 3) Grants for CG_ORDER_MANAGER
--------------------------------------------------------
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."USERS" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, UPDATE ON "CARDGAME"."ORDERS" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, UPDATE ON "CARDGAME"."PAYMENTS" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."ORDER_DETAILS" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."VOUCHERS" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."PAYMENT_METHODS" TO CG_ORDER_MANAGER'); END;
/

--------------------------------------------------------
-- 4) Grants for CG_INVENTORY_MANAGER
--------------------------------------------------------
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."PRODUCTS" TO CG_INVENTORY_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."CATEGORIES" TO CG_INVENTORY_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."PRODUCT_CATEGORIES" TO CG_INVENTORY_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."INVENTORY" TO CG_INVENTORY_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."TCG_SET" TO CG_INVENTORY_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."TCG_CARD" TO CG_INVENTORY_MANAGER'); END;
/

--------------------------------------------------------
-- 5) Grants for CG_ADMIN
--------------------------------------------------------
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."USERS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."PRODUCTS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."CATEGORIES" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."PRODUCT_CATEGORIES" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."INVENTORY" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."ORDERS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."ORDER_DETAILS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."PAYMENTS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."PAYMENT_METHODS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."REFRESH_TOKENS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."REVIEWS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."TCG_SET" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."TCG_CARD" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."USER_ADDRESSES" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."VOUCHERS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."WISHLISTS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."VW_USERS_PUBLIC" TO CG_ADMIN'); END;
/

--------------------------------------------------------
-- 6) Execute rights for logic objects (if object exists)
--------------------------------------------------------
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT EXECUTE ON "CARDGAME"."FN_ORDER_TOTAL" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT EXECUTE ON "CARDGAME"."SP_BACKUP_ORDERS" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT EXECUTE ON "CARDGAME"."SP_UPSERT_PAYMENT" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT EXECUTE ON "CARDGAME"."SP_BACKUP_ORDERS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT EXECUTE ON "CARDGAME"."SP_UPSERT_PAYMENT" TO CG_ADMIN'); END;
/
COMMIT;

--------------------------------------------------------
-- 7) Optional: assign roles to DB users (edit usernames)
--------------------------------------------------------
-- GRANT CG_APP_USER TO CARDGAME_APP;
-- GRANT CG_ORDER_MANAGER TO CARDGAME_ORDER;
-- GRANT CG_INVENTORY_MANAGER TO CARDGAME_WAREHOUSE;
-- GRANT CG_ADMIN TO CARDGAME_ADMIN;

--------------------------------------------------------
-- 8) Oracle Native Unified Audit policies (run as DBA)
--------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE AUDIT POLICY cg_audit_orders_payments
            ACTIONS UPDATE ON "CARDGAME"."ORDERS",
                    INSERT ON "CARDGAME"."PAYMENTS",
                    UPDATE ON "CARDGAME"."PAYMENTS"
    ]';
EXCEPTION
    WHEN OTHERS THEN
        -- ORA-46377: policy already exists
        -- ORA-01031: insufficient privileges
        IF SQLCODE NOT IN (-46377, -1031) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'AUDIT POLICY cg_audit_orders_payments';
EXCEPTION
    WHEN OTHERS THEN
        -- Ignore if already enabled or lack privilege
        IF SQLCODE NOT IN (-46361, -1031) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE AUDIT POLICY cg_audit_inventory
            ACTIONS UPDATE ON "CARDGAME"."INVENTORY"
    ]';
EXCEPTION
    WHEN OTHERS THEN
        -- ORA-46377: policy already exists
        -- ORA-01031: insufficient privileges
        IF SQLCODE NOT IN (-46377, -1031) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'AUDIT POLICY cg_audit_inventory';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-46361, -1031) THEN
            RAISE;
        END IF;
END;
/

--------------------------------------------------------
-- 9) Verify role grants
--------------------------------------------------------
-- Requires data dictionary privileges
-- SELECT GRANTEE, PRIVILEGE, OWNER, TABLE_NAME
-- FROM DBA_TAB_PRIVS
-- WHERE GRANTEE IN ('CG_APP_USER', 'CG_ORDER_MANAGER', 'CG_INVENTORY_MANAGER', 'CG_ADMIN')
--   AND OWNER = 'CARDGAME'
-- ORDER BY GRANTEE, OWNER, TABLE_NAME, PRIVILEGE;

--------------------------------------------------------
-- 10) Verify unified audit activity
--------------------------------------------------------
-- Requires audit view privileges
-- SELECT EVENT_TIMESTAMP, DBUSERNAME, ACTION_NAME, OBJECT_SCHEMA, OBJECT_NAME,
--        UNIFIED_AUDIT_POLICIES, RETURN_CODE
-- FROM UNIFIED_AUDIT_TRAIL
-- WHERE OBJECT_SCHEMA = 'CARDGAME'
--   AND OBJECT_NAME IN ('ORDERS', 'PAYMENTS', 'INVENTORY')
-- ORDER BY EVENT_TIMESTAMP DESC;
