--------------------------------------------------------
--  File created - Sunday-April-05-2026
--  Purpose: Cover DB scoring items (function/procedure/trigger/constraints
--           clean data/authorization/data security/backup-store)
--  Note: Run with schema CARDGAME
--------------------------------------------------------

--------------------------------------------------------
-- 0) Create DB roles (Phan quyen o DB)
--------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE CG_APP_USER';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-1921, -1031) THEN RAISE; END IF; -- role exists or no privilege
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE CG_ORDER_MANAGER';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-1921, -1031) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE CG_INVENTORY_MANAGER';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-1921, -1031) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE CG_ADMIN';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-1921, -1031) THEN RAISE; END IF;
END;
/

--------------------------------------------------------
-- 1) Integrity constraints (Rang buoc toan ven)
--------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF; -- already has primary key
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."CATEGORIES" ADD CONSTRAINT "PK_CATEGORIES" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."PRODUCTS" ADD CONSTRAINT "PK_PRODUCTS" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."INVENTORY" ADD CONSTRAINT "PK_INVENTORY" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."ORDERS" ADD CONSTRAINT "PK_ORDERS" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."ORDER_DETAILS" ADD CONSTRAINT "PK_ORDER_DETAILS" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."PAYMENTS" ADD CONSTRAINT "PK_PAYMENTS" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."PAYMENT_METHODS" ADD CONSTRAINT "PK_PAYMENT_METHODS" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."PRODUCT_CATEGORIES" ADD CONSTRAINT "PK_PRODUCT_CATEGORIES" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."REFRESH_TOKENS" ADD CONSTRAINT "PK_REFRESH_TOKENS" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."REVIEWS" ADD CONSTRAINT "PK_REVIEWS" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."USER_ADDRESSES" ADD CONSTRAINT "PK_USER_ADDRESSES" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."VOUCHERS" ADD CONSTRAINT "PK_VOUCHERS" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."WISHLISTS" ADD CONSTRAINT "PK_WISHLISTS" PRIMARY KEY ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."TCG_SET" ADD CONSTRAINT "PK_TCG_SET" PRIMARY KEY ("SET_ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."TCG_CARD" ADD CONSTRAINT "PK_TCG_CARD" PRIMARY KEY ("CARD_ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2260 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."USERS" ADD CONSTRAINT "UQ_USERS_EMAIL" UNIQUE ("EMAIL")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2261 THEN RAISE; END IF; -- unique already exists
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."PRODUCTS" ADD CONSTRAINT "UQ_PRODUCTS_SKU" UNIQUE ("SKU")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2261 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."VOUCHERS" ADD CONSTRAINT "UQ_VOUCHERS_CODE" UNIQUE ("CODE")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2261 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."INVENTORY" ADD CONSTRAINT "UQ_INVENTORY_PRODUCT" UNIQUE ("PRODUCT_ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2261 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."WISHLISTS" ADD CONSTRAINT "UQ_WISHLISTS_USER_PRODUCT" UNIQUE ("USER_ID", "PRODUCT_ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2261 THEN RAISE; END IF;
END;
/

-- Normalize legacy statuses before adding CHECK constraints.
UPDATE "CARDGAME"."ORDERS"
   SET "ORDER_STATUS" = CASE
        WHEN "ORDER_STATUS" IS NULL THEN 'PENDING'
        WHEN UPPER(TRIM("ORDER_STATUS")) IN ('PENDING', 'CONFIRMED', 'SHIPPING', 'COMPLETED', 'CANCELLED')
            THEN UPPER(TRIM("ORDER_STATUS"))
        WHEN UPPER(TRIM("ORDER_STATUS")) IN ('SHIPPED', 'DELIVERING') THEN 'SHIPPING'
        WHEN UPPER(TRIM("ORDER_STATUS")) IN ('DONE', 'SUCCESS') THEN 'COMPLETED'
        WHEN UPPER(TRIM("ORDER_STATUS")) IN ('CANCELED', 'CANCEL', 'FAILED', 'ERROR') THEN 'CANCELLED'
        ELSE 'PENDING'
   END;

UPDATE "CARDGAME"."PAYMENTS"
   SET "STATUS" = CASE
        WHEN "STATUS" IS NULL THEN 'PENDING'
        WHEN UPPER(TRIM("STATUS")) IN ('PENDING', 'PAID', 'FAILED', 'CANCELLED')
            THEN UPPER(TRIM("STATUS"))
        WHEN UPPER(TRIM("STATUS")) IN ('SUCCESS', 'COMPLETED') THEN 'PAID'
        WHEN UPPER(TRIM("STATUS")) IN ('CANCELED', 'CANCEL', 'ERROR') THEN 'CANCELLED'
        ELSE 'PENDING'
   END;

COMMIT;

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."ORDERS" ADD CONSTRAINT "CHK_ORDERS_STATUS" CHECK ("ORDER_STATUS" IN (''PENDING'', ''CONFIRMED'', ''SHIPPING'', ''COMPLETED'', ''CANCELLED''))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2264 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."PAYMENTS" ADD CONSTRAINT "CHK_PAYMENTS_STATUS" CHECK ("STATUS" IN (''PENDING'', ''PAID'', ''FAILED'', ''CANCELLED''))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2264 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."PAYMENT_METHODS" ADD CONSTRAINT "CHK_PAYMENT_METHODS_ACTIVE" CHECK ("IS_ACTIVE" IN (0, 1))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2264 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."PRODUCTS" ADD CONSTRAINT "CHK_PRODUCTS_ACTIVE" CHECK ("IS_ACTIVE" IN (0, 1))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2264 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."INVENTORY" ADD CONSTRAINT "FK_INVENTORY_PRODUCT" FOREIGN KEY ("PRODUCT_ID") REFERENCES "CARDGAME"."PRODUCTS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."ORDERS" ADD CONSTRAINT "FK_ORDERS_CUSTOMER_ID" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CARDGAME"."USERS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."ORDERS" ADD CONSTRAINT "FK_ORDERS_VOUCHER_ID" FOREIGN KEY ("VOUCHER_ID") REFERENCES "CARDGAME"."VOUCHERS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."ORDERS" ADD CONSTRAINT "FK_ORDERS_PM_ID" FOREIGN KEY ("PAYMENT_METHOD_ID") REFERENCES "CARDGAME"."PAYMENT_METHODS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."ORDER_DETAILS" ADD CONSTRAINT "FK_ORDER_DETAILS_ORDER_ID" FOREIGN KEY ("ORDER_ID") REFERENCES "CARDGAME"."ORDERS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."ORDER_DETAILS" ADD CONSTRAINT "FK_ORDER_DETAILS_PRODUCT_ID" FOREIGN KEY ("PRODUCT_ID") REFERENCES "CARDGAME"."PRODUCTS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."PAYMENTS" ADD CONSTRAINT "FK_PAYMENTS_ORDER_ID" FOREIGN KEY ("ORDER_ID") REFERENCES "CARDGAME"."ORDERS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."PAYMENTS" ADD CONSTRAINT "FK_PAYMENTS_PM_ID" FOREIGN KEY ("PAYMENT_METHOD_ID") REFERENCES "CARDGAME"."PAYMENT_METHODS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."PRODUCT_CATEGORIES" ADD CONSTRAINT "FK_PC_PRODUCT_ID" FOREIGN KEY ("PRODUCT_ID") REFERENCES "CARDGAME"."PRODUCTS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."PRODUCT_CATEGORIES" ADD CONSTRAINT "FK_PC_CATEGORY_ID" FOREIGN KEY ("CATEGORY_ID") REFERENCES "CARDGAME"."CATEGORIES" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."REFRESH_TOKENS" ADD CONSTRAINT "FK_RT_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "CARDGAME"."USERS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."REVIEWS" ADD CONSTRAINT "FK_REVIEWS_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "CARDGAME"."USERS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."REVIEWS" ADD CONSTRAINT "FK_REVIEWS_PRODUCT_ID" FOREIGN KEY ("PRODUCT_ID") REFERENCES "CARDGAME"."PRODUCTS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."REVIEWS" ADD CONSTRAINT "FK_REVIEWS_ORDER_ID" FOREIGN KEY ("ORDER_ID") REFERENCES "CARDGAME"."ORDERS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."USER_ADDRESSES" ADD CONSTRAINT "FK_UA_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "CARDGAME"."USERS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."WISHLISTS" ADD CONSTRAINT "FK_WISHLISTS_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "CARDGAME"."USERS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."WISHLISTS" ADD CONSTRAINT "FK_WISHLISTS_PRODUCT_ID" FOREIGN KEY ("PRODUCT_ID") REFERENCES "CARDGAME"."PRODUCTS" ("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."TCG_CARD" ADD CONSTRAINT "FK_TCG_CARD_SET_ID" FOREIGN KEY ("SET_ID") REFERENCES "CARDGAME"."TCG_SET" ("SET_ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -2270, -2264) THEN RAISE; END IF;
END;
/

--------------------------------------------------------
-- 2) Clean data scripts (Du lieu sach)
--------------------------------------------------------
UPDATE "CARDGAME"."USERS"
SET "EMAIL" = LOWER(TRIM("EMAIL")),
    "ROLE" = UPPER(TRIM("ROLE"))
WHERE "EMAIL" IS NOT NULL
   OR "ROLE" IS NOT NULL;

DELETE FROM "CARDGAME"."WISHLISTS" w
WHERE w.ROWID IN (
    SELECT rid
    FROM (
        SELECT ROWID AS rid,
               ROW_NUMBER() OVER (PARTITION BY "USER_ID", "PRODUCT_ID" ORDER BY "ID") AS rn
        FROM "CARDGAME"."WISHLISTS"
    ) x
    WHERE x.rn > 1
);

COMMIT;

--------------------------------------------------------
-- 3) Function (Create func)
--------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION "CARDGAME"."FN_ORDER_TOTAL"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE FUNCTION "CARDGAME"."FN_ORDER_TOTAL" (
    p_order_id IN NUMBER
) RETURN NUMBER
IS
    v_total NUMBER := 0;
BEGIN
    SELECT NVL(SUM(NVL("PRICE", 0) * NVL("QUANTITY", 0)), 0)
      INTO v_total
      FROM "CARDGAME"."ORDER_DETAILS"
     WHERE "ORDER_ID" = p_order_id;

    RETURN v_total;
END;
/

--------------------------------------------------------
-- 4) Procedures (Backup/Store + CRUD logic)
--------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE "CARDGAME"."ORDERS_BACKUP" (
            "BACKUP_ID" NUMBER GENERATED ALWAYS AS IDENTITY,
            "ORDER_ID" NUMBER,
            "CUSTOMER_ID" NUMBER,
            "AMOUNT" NUMBER(12,0),
            "DISCOUNT_AMOUNT" NUMBER(12,0),
            "SHIPPING_ADDRESS" NVARCHAR2(300),
            "ORDER_EMAIL" VARCHAR2(200),
            "NOTE" NVARCHAR2(500),
            "PAYMENT_METHOD_ID" NUMBER,
            "ORDER_DATE" DATE,
            "ORDER_STATUS" VARCHAR2(20),
            "BACKUP_AT" DATE DEFAULT SYSDATE,
            CONSTRAINT "PK_ORDERS_BACKUP" PRIMARY KEY ("BACKUP_ID")
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF; -- table already exists
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE "CARDGAME"."SP_BACKUP_ORDERS"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE PROCEDURE "CARDGAME"."SP_BACKUP_ORDERS" (
    p_from_date IN DATE,
    p_to_date   IN DATE
)
IS
BEGIN
    INSERT INTO "CARDGAME"."ORDERS_BACKUP" (
        "ORDER_ID", "CUSTOMER_ID", "AMOUNT", "DISCOUNT_AMOUNT", "SHIPPING_ADDRESS",
        "ORDER_EMAIL", "NOTE", "PAYMENT_METHOD_ID", "ORDER_DATE", "ORDER_STATUS"
    )
    SELECT "ID", "CUSTOMER_ID", "AMOUNT", "DISCOUNT_AMOUNT", "SHIPPING_ADDRESS",
           "ORDER_EMAIL", "NOTE", "PAYMENT_METHOD_ID", "ORDER_DATE", "ORDER_STATUS"
      FROM "CARDGAME"."ORDERS"
     WHERE "ORDER_DATE" >= TRUNC(p_from_date)
       AND "ORDER_DATE" < TRUNC(p_to_date) + 1;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE "CARDGAME"."SP_UPSERT_PAYMENT"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE PROCEDURE "CARDGAME"."SP_UPSERT_PAYMENT" (
    p_order_id          IN NUMBER,
    p_payment_method_id IN NUMBER,
    p_amount            IN NUMBER,
    p_status            IN VARCHAR2,
    p_transaction_id    IN VARCHAR2
)
IS
    v_id NUMBER;
BEGIN
    SELECT "ID"
      INTO v_id
      FROM "CARDGAME"."PAYMENTS"
     WHERE "ORDER_ID" = p_order_id
       AND ROWNUM = 1;

    UPDATE "CARDGAME"."PAYMENTS"
       SET "PAYMENT_METHOD_ID" = p_payment_method_id,
           "AMOUNT" = p_amount,
           "STATUS" = p_status,
           "TRANSACTION_ID" = p_transaction_id
     WHERE "ID" = v_id;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO "CARDGAME"."PAYMENTS" (
            "ORDER_ID", "PAYMENT_METHOD_ID", "AMOUNT", "STATUS", "TRANSACTION_ID"
        ) VALUES (
            p_order_id, p_payment_method_id, p_amount, p_status, p_transaction_id
        );
END;
/

--------------------------------------------------------
-- 5) Triggers (Create trigger + GUI logic support)
--------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "CARDGAME"."TRG_USERS_NORMALIZE"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE TRIGGER "CARDGAME"."TRG_USERS_NORMALIZE"
BEFORE INSERT OR UPDATE ON "CARDGAME"."USERS"
FOR EACH ROW
BEGIN
    :NEW."EMAIL" := LOWER(TRIM(:NEW."EMAIL"));
    :NEW."ROLE" := UPPER(TRIM(:NEW."ROLE"));
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "CARDGAME"."TRG_PAYMENTS_SET_PAID_AT"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE TRIGGER "CARDGAME"."TRG_PAYMENTS_SET_PAID_AT"
BEFORE INSERT OR UPDATE OF "STATUS" ON "CARDGAME"."PAYMENTS"
FOR EACH ROW
BEGIN
    IF :NEW."STATUS" = 'PAID' AND :NEW."PAID_AT" IS NULL THEN
        :NEW."PAID_AT" := SYSDATE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "CARDGAME"."TRG_PAYMENTS_CONFIRM_ORDER"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE TRIGGER "CARDGAME"."TRG_PAYMENTS_CONFIRM_ORDER"
AFTER INSERT OR UPDATE OF "STATUS" ON "CARDGAME"."PAYMENTS"
FOR EACH ROW
BEGIN
    IF :NEW."STATUS" = 'PAID' THEN
        UPDATE "CARDGAME"."ORDERS"
           SET "ORDER_STATUS" = 'CONFIRMED'
         WHERE "ID" = :NEW."ORDER_ID"
           AND "ORDER_STATUS" = 'PENDING';
    ELSIF :NEW."STATUS" IN ('FAILED', 'CANCELLED') THEN
        UPDATE "CARDGAME"."ORDERS"
           SET "ORDER_STATUS" = 'CANCELLED'
         WHERE "ID" = :NEW."ORDER_ID"
           AND "ORDER_STATUS" = 'PENDING';
    END IF;
END;
/

--------------------------------------------------------
-- 6) Data security (An toan du lieu)
--------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW "CARDGAME"."VW_USERS_PUBLIC"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE VIEW "CARDGAME"."VW_USERS_PUBLIC" AS
SELECT "ID", "EMAIL", "FULL_NAME", "COUNTRY", "PHONE", "ROLE", "CREATED_AT"
  FROM "CARDGAME"."USERS";
/

CREATE OR REPLACE PROCEDURE "CARDGAME"."SP_SAFE_GRANT" (
    p_sql IN VARCHAR2
)
IS
BEGIN
    EXECUTE IMMEDIATE p_sql;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-1917, -1031) THEN
            RAISE;
        END IF;
END;
/

--------------------------------------------------------
-- 7) Grant privileges by role (Phan quyen DB)
--------------------------------------------------------
-- Customer app role
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."PRODUCTS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."CATEGORIES" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."PRODUCT_CATEGORIES" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."INVENTORY" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."VOUCHERS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."PAYMENT_METHODS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."TCG_SET" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."TCG_CARD" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."VW_USERS_PUBLIC" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."USER_ADDRESSES" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."WISHLISTS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE ON "CARDGAME"."ORDERS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE ON "CARDGAME"."ORDER_DETAILS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE ON "CARDGAME"."PAYMENTS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."REFRESH_TOKENS" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."REVIEWS" TO CG_APP_USER'); END;
/

-- Order manager role
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."USERS" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, UPDATE ON "CARDGAME"."ORDERS" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, UPDATE ON "CARDGAME"."PAYMENTS" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."ORDER_DETAILS" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."VOUCHERS" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."PAYMENT_METHODS" TO CG_ORDER_MANAGER'); END;
/

-- Inventory manager role
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."PRODUCTS" TO CG_INVENTORY_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."CATEGORIES" TO CG_INVENTORY_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."PRODUCT_CATEGORIES" TO CG_INVENTORY_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."INVENTORY" TO CG_INVENTORY_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."TCG_SET" TO CG_INVENTORY_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."TCG_CARD" TO CG_INVENTORY_MANAGER'); END;
/

-- Admin role
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."USERS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."PRODUCTS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."CATEGORIES" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."PRODUCT_CATEGORIES" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."INVENTORY" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."ORDERS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."ORDER_DETAILS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."PAYMENTS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."PAYMENT_METHODS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."REFRESH_TOKENS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."REVIEWS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."TCG_SET" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."TCG_CARD" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."USER_ADDRESSES" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."VOUCHERS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT, INSERT, UPDATE, DELETE ON "CARDGAME"."WISHLISTS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT SELECT ON "CARDGAME"."VW_USERS_PUBLIC" TO CG_ADMIN'); END;
/

-- Execute rights for logic objects
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT EXECUTE ON "CARDGAME"."FN_ORDER_TOTAL" TO CG_APP_USER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT EXECUTE ON "CARDGAME"."SP_BACKUP_ORDERS" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT EXECUTE ON "CARDGAME"."SP_UPSERT_PAYMENT" TO CG_ORDER_MANAGER'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT EXECUTE ON "CARDGAME"."SP_BACKUP_ORDERS" TO CG_ADMIN'); END;
/
BEGIN "CARDGAME"."SP_SAFE_GRANT"('GRANT EXECUTE ON "CARDGAME"."SP_UPSERT_PAYMENT" TO CG_ADMIN'); END;
/

--------------------------------------------------------
-- 8) Sample user-role assignment (optional)
--------------------------------------------------------
-- GRANT CG_APP_USER TO CARDGAME_APP;
-- GRANT CG_ORDER_MANAGER TO CARDGAME_ORDER;
-- GRANT CG_INVENTORY_MANAGER TO CARDGAME_WAREHOUSE;
-- GRANT CG_ADMIN TO CARDGAME_ADMIN;

COMMIT;
