-- Expand USERS.ROLE check constraint to support management roles.
-- Run this script once on Oracle schema CARDGAME.

ALTER TABLE "CARDGAME"."USERS" MODIFY ("ROLE" VARCHAR2(30 BYTE));
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "CARDGAME"."USERS" DROP CONSTRAINT "CHK_USER_ROLE"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            RAISE;
        END IF;
END;
/

ALTER TABLE "CARDGAME"."USERS" ADD CONSTRAINT "CHK_USER_ROLE"
CHECK ("ROLE" IN ('USER', 'ADMIN', 'ORDER_MANAGER', 'INVENTORY_MANAGER')) ENABLE;
/

-- Example role assignments (optional)
-- UPDATE "CARDGAME"."USERS" SET "ROLE" = 'ADMIN' WHERE UPPER("EMAIL") = 'ADMIN@CARDGAME.COM';
-- UPDATE "CARDGAME"."USERS" SET "ROLE" = 'ORDER_MANAGER' WHERE UPPER("EMAIL") = 'ORDER@CARDGAME.COM';
-- UPDATE "CARDGAME"."USERS" SET "ROLE" = 'INVENTORY_MANAGER' WHERE UPPER("EMAIL") = 'WAREHOUSE@CARDGAME.COM';
-- COMMIT;
